const students = [
{ name: "Brian",
  link: "Brian",
picture: "",
  python_trinket: "",
  jsfiddle: "",
  codepen: "" 
},
{ name: "Cyneathia",
  link: "Cyneathia",
picture: "",
  python_trinket: "",
  jsfiddle: "",
  codepen: "" 
},
{ name: "Daniel",
  link: "Daniel",
picture: "",
  python_trinket: "",
  jsfiddle: "",
  codepen: "" 
},
{ name: "Isaiah",
  link: "Isaiah",
picture: "",
  python_trinket: "",
  jsfiddle: "",
  codepen: "" 
},
{ name: "Jaiden",
  link: "Jaiden",
picture: "",
  python_trinket: "",
  jsfiddle: "",
  codepen: "" 
},
{ name: "Ja'Naye",
  link: "Ja'Naye",
picture: "",
  python_trinket: "",
  jsfiddle: "",
  codepen: "" 
},
{ name: "Janiece",
  link: "Janiece",
picture: "",
  python_trinket: "",
  jsfiddle: "",
  codepen: "" 
},
{ name: "Kanazja",
  link: "Kanazja",
picture: "",
  python_trinket: "",
  jsfiddle: "",
  codepen: "" 
},
{ name: "Mahkiah",
  link: "Mahkiah",
picture: "",
  python_trinket: "",
  jsfiddle: "",
  codepen: "" 
},
{ name: "Makayla",
  link: "Makayla",
picture: "",
  python_trinket: "",
  jsfiddle: "",
  codepen: "" 
},
{ name: "Mikal",
  link: "Mikal",
picture: "",
  python_trinket: "",
  jsfiddle: "",
  codepen: "" 
},
{ name: "Na'Leah",
  link: "Na'Leah",
picture: "",
  python_trinket: "",
  jsfiddle: "",
  codepen: "" 
},
{ name: "Nasir",
  link: "Nasir",
picture: "",
  python_trinket: "",
  jsfiddle: "",
  codepen: "" 
},
{ name: "Peyton",
  link: "Peyton",
picture: "",
  python_trinket: "",
  jsfiddle: "",
  codepen: "" 
},
{ name: "Raelyn",
  link: "Raelyn",
picture: "",
  python_trinket: "",
  jsfiddle: "",
  codepen: "" 
},
{ name: "Robert",
  link: "Robert",
picture: "",
  python_trinket: "",
  jsfiddle: "",
  codepen: "" 
},
{ name: "Shamir",
  link: "Shamir",
picture: "",
  python_trinket: "",
  jsfiddle: "",
  codepen: "" 
}
];
